### ISSUE TITLE
Merge with Code Block macro

### ISSUE THREAD

**Issue by AmonBune** [chhantyal/code-syntax-highlighter#2]
I don't know if it is possible, but it would be convenient and less confusing, if the features of the code syntax highlighter could be integrated into the built-in Code Block macro. Right now you have the "Code Block" and "Code Syntax Highlighter" macros side-by-side and if you select the normal Code Block, you will get the native, ugly code block instead of the syntax highlighter one.

An alternative would be to disable the native code block, but I don't know if that is possible.

**Comment by chhantyal** [comment]
@AmonBune Thanks for taking time to raise this issue. Original Code block macro come with Confluence, which means it is likely not possible to disable.

Code Syntax Highlighter is third party plugin. I understand your concern & it is valid, unfortunately looks like it's not possible.

Meanwhile, Code Syntax Highlighter is quite new plugin & I would love to get user feedbacks. May I contact you via email for feedback?
