### ISSUE TITLE
Can't install from atlassian marketplace at the moment

### ISSUE THREAD

**Issue by TheJohny** [chhantyal/code-syntax-highlighter#3]
Hi!
I get 404 error when I try to install the app from the marketplace.
From this link:
https://marketplace.atlassian.com/apps/1219685/code-syntax-highlighter?hosting=cloud&tab=support
I get this one when I press the "Get it now" button: 
https://<mydomain>.atlassian.net/plugins/servlet/upm/marketplace/plugins/code-prettify
but it drops a 404 page not found error. 

Do you get the same?

Best!

**Comment by chhantyal** [comment]
Hi @TheJohny 

This is I think related to marketplace issue. I was about to bypass this issue and install from `Find new addons` in Confluence setting.

Just add your subdomain in following url & you should get the addon:

https://[your subdomain].atlassian.net/wiki/plugins/servlet/upm/marketplace/search?q=code syntax

Or
1. Click `Find new addons` in Confluence setting
2. Type `code syntax` in search box. You should see Code Syntax Highlighter there.

**Comment by TheJohny** [comment]
You're right. It worked that way. Thank you for your help! :)
