### ISSUE TITLE
Unable to find in Macros in newest cloud version of Confluence

### ISSUE THREAD

**Issue by asherdowd** [chhantyal/code-syntax-highlighter#4]
Have a trial installed in newest version of Confluence Cloud version.
Go to insert a Macro to a page and I am unable to locate Code Sytax anywhere in the list of 'more macros'.

**Comment by sethdowd** [comment]
The issue is resolved.  It took about 15 minutes from the time the App was installed until it became available for use in the Macro selection.

**Comment by chhantyal** [comment]
Hi @sethdowd , are you still facing issue?
I was able to find it using top bar menu, see screenshots in this thread https://github.com/chhantyal/code-syntax-highlighter/issues/7#issuecomment-536473610
