### ISSUE TITLE
Using it on a page with the "new editing experience" results in "__confluenceADFMigration­Unsupported­ContentInternalExtension__" error"

### ISSUE THREAD

**Issue by frankvaneykelen** [chhantyal/code-syntax-highlighter#5]
When I create a page with the "new editing experience":

![image](https://user-images.githubusercontent.com/525891/61210331-6f40d500-a6fc-11e9-95f4-2892dd7d3494.png)

and invoke the Code Syntax Highlighter macro via `/code`:

![image](https://user-images.githubusercontent.com/525891/61210396-a8794500-a6fc-11e9-8d5b-6d280053d49b.png)

and publish, the formatting is not applied and when I edit again I see this:

![image](https://user-images.githubusercontent.com/525891/61210451-db233d80-a6fc-11e9-82e9-53a9bb75a6c8.png)

`__confluenceADFMigrationUnsupportedContentInternalExtension__`

**Comment by chhantyal** [comment]
Thank you for reporting this issue. New editing experience is not yet supported, we will have a update the addon soon.

**Comment by chhantyal** [comment]
For others facing this issue: looks like this is quite complex issue and lots of plugins are affected. Atlassian hasn't provided easy way to migrate yet, so it might take some time to fix this. For now, please use old editing interface as new interface has many issues.

See thread here in[ Atlassian community forum](https://community.atlassian.com/t5/Confluence-discussions/Try-out-the-new-editing-experience/td-p/1000813#M3644)

**Comment by chhantyal** [comment]
Hi @frankvaneykelen , this add-on now works in new editing experience 🎉 Could you please try again?

Let me know if you are still facing problem. Thank you

**Comment by frankvaneykelen** [comment]
Hi @chhantyal, I can confirm that it works now. Thanks!

**Comment by chhantyal** [comment]
Glad that it works. Thanks for raising this ticket 👍
