### ISSUE TITLE
I can't find a way to use it with the new cloud editor

### ISSUE THREAD

**Issue by mcmorry** [chhantyal/code-syntax-highlighter#7]
Is it compatible with the new cloud editor for Confluence?
I don't have access to the "Macro" option.
Please advice.
Thanks

**Comment by chhantyal** [comment]
Hi @mcmorry , thank you for raising this issue.
Currently, this macro does not support new cloud editor. Atlassian has not provided migration path for add-on developers yet and it is not clear how all the add-ons like CSH will support new editor.

Until there is migration path, we recommend users to use old editor. Thank you

**Comment by chhantyal** [comment]
Hi @mcmorry ,
I tried with new editor and there is macro option, see below screenshots:

- Click on insert + button at top bar
![Screen Shot 2019-09-30 at 11 03 59](https://user-images.githubusercontent.com/862941/65864530-50082a00-e372-11e9-8683-3aa2c46b4600.png)
- Click `... View more` at the end of the panel and you will get macro UI.
![Screen Shot 2019-09-30 at 11 04 18](https://user-images.githubusercontent.com/862941/65864601-6e6e2580-e372-11e9-914a-eadb3cc44270.png)

That way you can use macros like CSH. Looks like Confluence has removed old option where you could just type `{` to go to macro ui.

Please let me know if you are still facing issue. Thanks

**Comment by mcmorry** [comment]
Thank you! I'll try that.
