### ISSUE TITLE
Coldfusion is not included in languages dropdown

### ISSUE THREAD

**Issue by chrisn6361** [chhantyal/code-syntax-highlighter#9]
Hi,

According to this page below Coldfusion should be supported.
https://bitwelt.atlassian.net/wiki/spaces/CSH/pages/354942981/Supported+languages

However, I did not see it listed in the languages dropdown.

Please advise.

**Comment by chhantyal** [comment]
Hi @chrisn6361, you can use auto-detect feature if a language is not listed there. Could you please try it and let us know?

**Comment by chrisn6361** [comment]
Auto-detect seems to work for CF code.  However, the line numbers and code do not line up correctly (attached).

![2021-10-28_06-59-50](https://user-images.githubusercontent.com/855328/139243296-081ab05d-0f85-4f93-b8c2-7ea64464126c.png)
